# This is a basic workflow to help you get started with Actions

name: Verdaccio-CI

on:
  push:
 
jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Spin Up Private NPM
      uses: Grants52/gha-test@v2
      with:
        args: -d  
    
    - name: Confirm version   
      run: cat /etc/*eleas*
         
            
          
   
