name: Verdaccio-CI

on:
  push:
    
jobs:
  verdaccio-docker:
   runs-on: ubuntu-latest
   container: 
    image: verdaccio/verdaccio:4
   steps: 
    
      - name: log node version
        run : |
          node -v
          cat /etc/*eleas*
          chown -R verdaccio $HOME
          
      - uses: actions/checkout@v1  
      - name: Configure Verdaccio1
        uses: docker://verdaccio/verdaccio:4
        with:
          entrypoint: /bin/cp
          args: "config.yaml /config.yaml"
      
      - uses: actions/checkout@v1  
      - name: Configure Verdaccio2
        uses: docker://verdaccio/verdaccio:4
        with:
          entrypoint: ./entrypoint.sh
     
     
      - name: log node version2
        run : |
          node -v
          cat /etc/*eleas*
         
            
          
   
