name: Verdaccio-CI

on:
  push:
    
jobs:
  verdaccio-docker:
   runs-on: ubuntu-latest
   container: 
    image: node:12
    
   steps: 
      - uses: actions/checkout@v1 
      - name: Install Verdaccio
        run : |
          npm install -g verdaccio
          npm install -g verdaccio-auth-memory
          npm install -g verdaccio-memory
          npm install -g npm-auth-to-token
          
      - name : Copy config
        run  : config.yaml /config.yaml
      
      - uses: actions/checkout@v1  
      - name: Configure Verdaccio2
        uses: docker://node:12
        with:
          entrypoint: ./entrypoint.sh
     
     
      - name: log node version2
        run : |
          node -v
          cat /etc/*eleas*
         
            
          
   
