# This is a basic workflow to help you get started with Actions

name: Verdaccio-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    
jobs:
  testVerdaccio:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Install Verdaccio
        run : |
          docker pull verdaccio/verdaccio:4
          docker run -it --rm --name verdaccio -p 4873:4873 verdaccio
