# This is a basic workflow to help you get started with Actions

name: Verdaccio-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    
jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1
    #- name: Publish
      uses: verdaccio/github-actions/publish@master
      with:
        args: -d
     
        
      

