name: Slack-test

on:
  push:
   
jobs:
     test_slack_messaging:
      runs-on: ubuntu-latest
      
      steps:

      
      - name: Send Slack message
        run: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"${{github.workflow}} workflow has completed with status ${{job.status}} <${{github.event.commits.author.username}} | check it out now>"}' \
            '${{ secrets.SLACK_WEBHOOK }}'
            
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
