name: Smoke-Testing
env:
  LOCAL_REGISTRY: "http://0.0.0.0:4873"

on:
  push:

jobs:
     test_verdaccio_pipeline:
      runs-on: ubuntu-latest
      
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2  
          
        - name: Install Verdaccio
          run: |
            sudo npm install -g verdaccio
            sudo npm install -g verdaccio-auth-memory
            sudo npm install -g verdaccio-memory
            sudo npm install -g npm-auth-to-token
            
        - name: Configure Verdaccio
          run: |
            cat <<EOF >config.yaml
            auth:
              auth-memory:
                users:
                  foo:
                    name: test
                    password: test
            store:
              memory:
                limit: 1000
            ## we don't need any remote request
            uplinks:
            packages:
              '@*/*':
                access: \$all
                publish: \$all
              '**':
                access: \$all
                publish: \$all
            middlewares:
              audit:
                enabled: true
            logs:
             - {type: stdout, format: pretty, level: trace}
            EOF
            
            
            local_registry="http://0.0.0.0:4873"
            tmp_registry_log=`mktemp`
            mkdir -p .config/verdaccio
            cp --verbose config.yaml .config/verdaccio/config.yaml
            nohup verdaccio --config .config/verdaccio/config.yaml &>$tmp_registry_log &
            npm-auth-to-token -u test -p test -e test@test.com -r ${{env.LOCAL_REGISTRY}}
            cat .config/verdaccio/config.yaml
            
        - name: Publish packages
          run  : |
            npm publish --registry ${{env.LOCAL_REGISTRY}}
            
        - name: Install package
          run  : |
            sudo mkdir /test_install
            cd /test_install
            npm install hello-world-appgs
            ls -l
