name: Smoke-Testing

on:
  push:

jobs:
     test_verdaccio_pipeline:
      runs-on: ubuntu-latest
      
      steps:
        - name: Git clone repository
          uses: actions/checkout@v2  
          
        - name: Install Verdaccio
          run: |
            sudo npm install -g verdaccio
            sudo npm install -g verdaccio-auth-memory
            sudo npm install -g verdaccio-memory
            sudo npm install -g npm-auth-to-token
            
        - name: Configure Verdaccio
          run: |
            cat <<EOF >config.yaml
            auth:
              auth-memory:
                users:
                  foo:
                    name: test
                    password: test
            store:
              memory:
                limit: 1000
            ## we don't need any remote request
            uplinks:
            packages:
              '@*/*':
                access: $all
                publish: $all
              '**':
                access: $all
                publish: $all
            middlewares:
              audit:
                enabled: true
            logs:
             - {type: stdout, format: pretty, level: trace}
            EOF
            
            
            local_registry="http://localhost:4873/"
            tmp_registry_log=`mktemp`
            mkdir -p .config/verdaccio
            nohup verdaccio --config .config/verdaccio/config.yaml &>$tmp_registry_log &
            npm-auth-to-token -u test -p test -e test@test.com -r $local_registry
            npm publish --registry $local_registry
